### ISSUE TITLE
Read breakpoints from tailwind.config.js

### ISSUE THREAD

**Issue by Shackless** [ShipBit/svane#1]
It would be great if Svane could just read the breakpoints from the Tailwind config file. 

More infos: https://stackoverflow.com/questions/71633327/referencing-tailwindcss-config-from-javascript-in-sveltekit

A quick attempt to do so failed, so I just added a TODO comment in the code.

**Comment by jwatts777** [comment]
~~I saw your WIP commit, and wrote this up. This seems to output the correct breakpoint object, assuming you were using the projects tailwind config, and following what I think is your object structure.~~



~~export const convertBreakpoints = (breakpoints) => {
    const convertedBreakpoints = {};~~
~~const breakpointKeys = Object.keys(breakpoints);
    for (let i = 0; i < breakpointKeys.length; i++) {
        const currentKey = breakpointKeys[i];
        const currentVal = parseInt(breakpoints[currentKey]); ~~
        if (i === 0) {
            // First breakpoint
			const nextKey = breakpointKeys[i + 1];
            const nextVal = parseInt(breakpoints[nextKey]);
            convertedBreakpoints[currentKey] = { max: nextVal - 1 };
        } else if (i === breakpointKeys.length - 1) {
            // Last breakpoint
            convertedBreakpoints[currentKey] = { min: currentVal };
        } else {
			// Other Breakpoints
            const nextKey = breakpointKeys[i + 1];
            const nextVal = parseInt(breakpoints[nextKey]);
            convertedBreakpoints[currentKey] = { min: currentVal, max: nextVal - 1 };
        }
    }
    console.log("convertedBreakpoints", convertedBreakpoints);
    return convertedBreakpoints;~~
};
	const testVar = convertBreakpoints(breakpoints)
	console.log("testVar", testVar)



~~Output:~~


~~{
    "sm": {
        "max": 767
    },
    "md": {
        "min": 768,
        "max": 1023
    },
    "lg": {
        "min": 1024,
        "max": 1279
    },
    "xl": {
        "min": 1280,
        "max": 1535
    },
    "2xl": {
        "min": 1536
    }
}~~



~~I could make larger changes, but I see that you're in the middle of reworking the project.~~

**Comment by jwatts777** [comment]
#3
I tested some basic changes to tailwind.config, just to make sure that the most obvious issues wouldn't spring up, and kept them in the pull request so that you can easily inspect them. Excited to put it to use.
![image](https://github.com/ShipBit/svane/assets/91865823/e63a4821-5755-4334-ba77-056f95e6c055)

**Comment by Shackless** [comment]
Yeah, I did some further work in this yesterday on the branch `tw-config` but couldn't finish it yet - I expect to continue this on Monday. 

Most of it seemed to be working already but I had some weird issue that the read Tailwind config was somehow "cached" in the client. So at some point I added some random breakpoints like "phone, mobile, tablet" in my TW config and after I removed and console.log'ed that, it would display the correct (default) values in the vite console (server) but the client still logged and showed the custom breakpoint from before.

My guess is that either something needs to be reactive in the Svelte component or this is caused by something that this vite config change does. That's why I want to investigate more first - and I also need to fix some of the docs when it's done.

Thanks for your PRs! I'll definitely merge them into my branch and hopefully resolve this issue soon. I'll ping you when it's done so that you can test with your configs.

**Comment by Shackless** [comment]
I think i can also remove these entire `{ min: 640 }` vs `{ min: '640px' }` shenanigans I implemented because if we read from the Tailwind config, the values will always be strings. I renamed `breakpoints` to `screens` because that's what it's called in the Tailwind config, so this will be breaking change / v2 anyways - no need to keep the old stuff alive.

**Comment by jwatts777** [comment]
Was wondering why you were up at 4 in the morning and realized you are German.

When I said tailwind changes (assuming you haven't looked at the code yet) I just meant a psuedo npm download/fresh install on blank project (2xl is 4 pixels larger than tailwind spec)

**Comment by jwatts777** [comment]
> Yeah, I did some further work in this yesterday on the branch `tw-config` but couldn't finish it yet - I expect to continue this on Monday.
> 
> Most of it seemed to be working already but I had some weird issue that the read Tailwind config was somehow "cached" in the client. So at some point I added some random breakpoints like "phone, mobile, tablet" in my TW config and after I removed and console.log'ed that, it would display the correct (default) values in the vite console (server) but the client still logged and showed the custom breakpoint from before.
> 
> My guess is that either something needs to be reactive in the Svelte component or this is caused by something that this vite config change does. That's why I want to investigate more first - and I also need to fix some of the docs when it's done.
> 
> Thanks for your PRs! I'll definitely merge them into my branch and hopefully resolve this issue soon. I'll ping you when it's done so that you can test with your configs.

I've never posted my own npm package, so I'm unfamiliar, but willing to help.

The code was a little unreadable without me changing some of them for my brain, lots of `Object.entries(breakpoint)` and `(const breakpoint in breakpoints)`

**Comment by Shackless** [comment]
> When I said tailwind changes (assuming you haven't looked at the code yet) I just meant a psuedo npm download/fresh install on blank project (2xl is 4 pixels larger than tailwind spec)

Good catch, thanks. I don't think we'll need to repeat the default config at all if it's done. If you don't specify any custom screens in the Tailwind config, the `config.theme.screens` prop will still have all the values, directly coming from TW.

Fair point with the scope override variable names, I'll incorporate that, too.

**Comment by jwatts777** [comment]
> I think i can also remove these entire `{ min: 640 }` vs `{ min: '640px' }` shenanigans I implemented because if we read from the Tailwind config, the values will always be strings. I renamed `breakpoints` to `screens` because that's what it's called in the Tailwind config, so this will be breaking change / v2 anyways - no need to keep the old stuff alive.

Pretty much. My implementation only uses the direct call of tailwind config, and then immediately does all screen changes right there in the function. I tried to keep as minimally invasive as possible. *Note that I did keep the same changes (tailwind config-wise) as you, but diverged heavily after making my config changes.* I personally like screens more than breakpoints, makes the code more readable.
In terms of replicating the weird vite config issue, I'll have to do more research and come back. I am experiencing it though, just had it happen. `2xl:1536`  instead of `1540`, refresh local server and suddenly it's back to `1540`.

This will be my last post for the night. 👋

**Comment by Shackless** [comment]
@jwatts777 I created a PR with various refactorings. Thanks for your input! I took some inspiration from your proposal but made it even easier I think. What do you think? 

I'll take a look at this weird Vite config thing tomorrow. In case you want to investigate, I'd suggest to take the code base in #5 (branch: `tw-config`) as base.
