### ISSUE TITLE
Server Side Rendering Support

### ISSUE THREAD

**Issue by jwatts777** [ShipBit/svane#6]
#4 - Relevant
https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window
Would need to test to confirm, but have used this on TS Particles for a Vercel deployment and had no issues. May also be related to the weird vite config issue.

**Comment by Shackless** [comment]
already used in #5. I'll test SSR more if the Vite config issue is resolved.

**Comment by jwatts777** [comment]
I made this before I saw #5 , will delete
