### ISSUE TITLE
Sticky Header + Component Width

### ISSUE THREAD

**Issue by jwatts777** [ShipBit/svane#7]
Thanks, can confirm that fixed the errors. Just a couple of other issues:

1/ I am using a sticky header and the component is hidden behind that - probably an idea to add a high z-index.
2/ The component only extends 25% of the screen width - maybe an idea to add `left: 0` and `right: 0` in addition to the `top: 0`, or use `inset` of course.

_Originally posted by @jeremypeters in https://github.com/ShipBit/svane/issues/4#issuecomment-1684894864_

**Comment by Shackless** [comment]
Thanks for the suggestions, I applied all of them!
